export const PATHS: string[] = [
  "./packages/components/src/Button/Button.tsx",
  "./packages/components/src/Alert/Alert.tsx",
  "./packages/components/src/Avatar/Avatar.tsx",
  "./packages/components/src/Badge/Badge.tsx",
  "./packages/components/src/Breadcrumbs/Breadcrumbs.tsx",
  "./packages/components/src/Card/Card.tsx",
  "./packages/components/src/Checkbox/Checkbox.tsx",
  "./packages/components/src/Divider/Divider.tsx",
  "./packages/components/src/Drawer/Drawer.tsx",
  "./packages/components/src/Dropdown/Dropdown.tsx",
  "./packages/components/src/Flex/Flex.tsx",
  "./packages/components/src/Image/Image.tsx",
  "./packages/components/src/InputNumber/InputNumber.tsx",
  "./packages/components/src/Layout/index.ts",
  "./packages/components/src/Loader/Loader.tsx",
  "./packages/components/src/Modal/Modal.tsx",
  "./packages/components/src/Notification/Notification.tsx",
  "./packages/components/src/Progress/Progress.tsx",
  "./packages/components/src/RadioButton/RadioButton.tsx",
  "./packages/components/src/RadioButton/RadioButtonGroup.tsx",
  "./packages/components/src/Select/Select.tsx",
  "./packages/components/src/Switch/Switch.tsx"
];

